global:
  scrape_interval: 1m
  evaluation_interval: 1m
  scrape_timeout: 50s
  

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']

  - job_name: "spring_petclinic"
    static_configs:
      - targets: ['host.docker.internal:12345']
  
